import streamlit as st

st.header(':orange[Identifikasi Ion Golongan I-V]', divider='rainbow')
st.write(':blue[Ion yang dapat diidentifikasi Ag+,Pb2+,Hg2+,Al3+,Fe3+,Ba2+,Sr2+,Ca2+]')
st.sidebar.markdown("# Cara Mengidentifikasi Ion Golongan")
with st.sidebar.container():
    st.image("https://acalpk.files.wordpress.com/2024/05/pemisahan-ion-kation.png?resize=219%2C219")

ion_identifikasi = st.text_input('Masukkan ion yang ingin diidentifikasi :')
if ion_identifikasi == "Ag+":
    st.write('Alat dan Bahan : Tabung Reaksi, Pipet tetes, Tabung Sentrifugasi, NH4OH, HCl encer, HNO3, Air Suling')
    st.write('Cara Kerja :')
    st.write('1. Cuci dan bilas tabung reaksi dengan air keran dan air suling, lalu dikeringkan')
    st.write('2. Masukkan sampel yang akan diidentifikasi ke dalam tabung reaksi sebanyak 1 drop')
    st.write('3. HCl encer dimasukkan sebanyak 1 drop kedalam tabung reaksi yang sudah diisikan sampel, lalu di centrifuge')
    st.write('4. Jika terbentuk endapan putih (AgCl) maka identifikasi dapat dilanjutkan, jika tidak maka sampel negatif mengandung ion Ag+')
    st.image('https://acalpk.files.wordpress.com/2024/05/bild0113.jpg?resize=219%2C219')
    st.write('5. Endapan yang terbentuk dipisahkan dengan larutannya, kemudian endapan dicuci dengan air suling sebanyak 2x sebanyak 1 drop. Lalu ditambahkan kembali 1 drop air suling hangat lalu dipanaskan')
    st.write('6. Jika masih terbentuk endapan putih setelah dipanaskan maka identifikasi dilanjutkan, jika endapan larut maka sampel negatif mengandung ion Ag+')
    st.write('7. Kemudian endapan kembali dipisahkan dengan larutan, kemudian ditambahkan NH4OH berlebih')
    st.write('8. Jika endapan larut setelah ditambahkan NH4OH maka identifikasi dapat dilanjutkan, jika masih terbentuk endapan maka sampel negatif mengandung ion Ag+')
    st.write('9. Sampel yang berbentuk larutan dipipet sebanyak 1 drop kedalam tabung reaksi baru, dan ditambahkan HNO3 sebanyak 10 tetes')
    st.write('10.Jika terbentuk endapan maka identifikasi selesai dilakukan dan sampel positif mengandung ion Ag+')
    st.write('Reaksi yang terjadi:')
    st.write('Ag+ + HCl -> AgCl (putih) + 2H+')
    st.write('AgCl (putih) + 2NH4OH -> [Ag(NH3)2]Cl + 2H2O')
    st.write('[Ag(NH3)2]Cl + 2HNO3 -> AgCl (putih) + 2NH4NO3')

elif ion_identifikasi == "Hg2+":
    st.write('Alat dan Bahan : Tabung Reaksi, Pipet tetes, Tabung Sentrifugasi, NH4OH, HCl encer, Air Suling')
    st.write('Cara Kerja :')
    st.write('1. Cuci dan bilas tabung reaksi dengan air keran dan air suling, lalu dikeringkan')
    st.write('2. Masukkan sampel yang akan diidentifikasi ke dalam tabung reaksi sebanyak 1 drop')
    st.write('3. HCl encer dimasukkan sebanyak 1 drop kedalam tabung reaksi yang sudah diisikan sampel, lalu di centrifuge')
    st.write('4. Jika terbentuk endapan putih (Hg2Cl2) maka identifikasi dapat dilanjutkan, jika tidak maka sampel negatif mengandung ion Hg2+')
    st.image('https://acalpk.files.wordpress.com/2024/05/bild0113.jpg?resize=219%2C219')
    st.write('5. Endapan yang terbentuk dipisahkan dengan larutannya, kemudian endapan dicuci dengan air suling sebanyak 2x sebanyak 1 drop. Lalu ditambahkan kembali 1 drop air suling hangat lalu dipanaskan')
    st.write('6. Jika masih terbentuk endapan putih setelah dipanaskan maka identifikasi dilanjutkan, jika endapan larut maka sampel negatif mengandung ion Hg2+')
    st.write('7. Kemudian endapan kembali dipisahkan dengan larutan, kemudian ditambahkan NH4OH berlebih')
    st.write('8. Jika terbentuk endapan maka identifikasi selesai dilakukan dan sampel positif mengandung ion Hg2+')
    st.write('Reaksi yang terjadi:')
    st.write('2Hg+ + 2HCl -> Hg2Cl2 (putih) + 2H+')
    st.write('Hg2Cl2 (putih) + 2NH4OH -> [Hg(Nh2)]Cl (putih) + 2H2O + NH4Cl + Hg (hitam)')


elif ion_identifikasi == "Pb2+":
    st.write('Alat dan Bahan : Tabung Reaksi, Pipet tetes, Tabung Sentrifugasi, NH4OH, HCl encer, Air Suling')
    st.write('Cara Kerja :')
    st.write('1. Cuci dan bilas tabung reaksi dengan air keran dan air suling, lalu dikeringkan')
    st.write('2. Masukkan sampel yang akan diidentifikasi ke dalam tabung reaksi sebanyak 1 drop')
    st.write('3. HCl encer dimasukkan sebanyak 1 drop kedalam tabung reaksi yang sudah diisikan sampel, lalu di centrifuge')
    st.write('4. Jika terbentuk endapan putih (PbCl2) maka identifikasi dapat dilanjutkan, jika tidak maka sampel negatif mengandung ion Pb+')
    st.image('https://acalpk.files.wordpress.com/2024/05/bild0113.jpg?resize=219%2C219')
    st.write('5. Endapan yang terbentuk dipisahkan dengan larutannya, kemudian endapan dicuci dengan air suling sebanyak 2x sebanyak 1 drop. Lalu ditambahkan kembali 1 drop air suling hangat lalu dipanaskan')
    st.write('6. Jika saat dipanaskan endapan larut maka identifikasi dapat dilanjutkan, jika terdapat endapan maka sampel negatif mengandung ion Pb2+')
    st.write('7. Endapan kemudian ditambahkan pereaksi K2CrO4 2-3 tetes akan terbentuk larutan kuning')
    st.write('8. Jika terbentuk larutan berwarna kuning maka identifikasi selesai dilakukan dan sampel positif mengandung ion Pb2+')
    st.write('Reaksi yang terjadi:')
    st.write('Pb2+ + 2HCl -> PbCl2 (putih) + 2H+')
    st.write('PbCl (putih) + H2O -> Pb2+ + 2Cl- +2H2O')
    st.write('Pb2+ + K2CrO4 -> PbCrO4 (kuning) + 2K+')

elif ion_identifikasi == "Al3+":
    st.write('Alat dan Bahan : Tabung Reaksi, Pipet tetes, Tabung Sentrifugasi, NH4OH, HCl encer, Air Suling')
    st.write('Cara Kerja :')
    st.write('1. Cuci dan bilas tabung reaksi dengan air keran dan air suling, lalu dikeringkan')
    st.write('2. Masukkan sampel yang akan diidentifikasi ke dalam tabung reaksi sebanyak 1 drop')
    st.write('3. HCl encer dimasukkan sebanyak 1 drop kedalam tabung reaksi yang sudah diisikan sampel, lalu di centrifuge')
    st.write('4. Jika tidak terbentuk endapan maka identifikasi dapat dilanjutkan, jika terbentuk endapan maka sampel negatif mengandung ion Al3+')
    st.write('5. Larutan ditambahkan NH4OH berlebih sampai terbentuk endapan putih Al(OH)3, kemudian endapan tersebut dipisahkan')
    st.image('https://acalpk.files.wordpress.com/2024/05/bild0113.jpg?resize=219%2C219')
    st.write('6. Endapan putih Al(OH)3 kemudian ditambahkan NaOH sebanyak 3 tetes, jika larut maka identifikasi dapat dilanjutkan. Jika terbentuk endapan maka sampel negatif mengandung ion Al3+')
    st.write('7. Larutan kemudian ditambahkan HCl sebanyak 2 tetes dan Na2CO3 sebanyak 3 tetes sampai terbentuk endapan putih')
    st.write('8. JIka terbentuk endapan putih maka identifikasi selesai dilakukan dan sampel positif mengandung ion Al3+')
    st.write('Reaksi yang terjadi:')
    st.write('Al3+ + NH4OH -> Al(OH)3 (putih) + NH4+')
    st.write('Al(OH)3 (putih) + NaOH -> Al(OH)4- + Na+')
    st.write('Al(OH)4- + HCl + Na2CO3 -> Al(OH)3 (putih) + 2NaCl + HCO3- +')

elif ion_identifikasi == "Fe3+":
    st.write('Alat dan Bahan : Tabung Reaksi, Pipet tetes, Tabung Sentrifugasi, NH4OH, HCl encer, Air Suling')
    st.write('Cara Kerja :')
    st.write('1. Cuci dan bilas tabung reaksi dengan air keran dan air suling, lalu dikeringkan')
    st.write('2. Masukkan sampel yang akan diidentifikasi ke dalam tabung reaksi sebanyak 1 drop')
    st.write('3. HCl encer dimasukkan sebanyak 1 drop kedalam tabung reaksi yang sudah diisikan sampel, lalu di centrifuge')
    st.write('4. Jika tidak terbentuk endapan maka identifikasi dapat dilanjutkan, jika terbentuk endapan maka sampel negatif mengandung ion Fe3+')
    st.write('5. Larutan ditambahkan NH4OH berlebih sampai terbentuk endapan cokelat Fe(OH)3, kemudian endapan tersebut dipisahkan')
    st.write('6. Endapan cokelat Fe(OH)3 kemudian ditambahkan NaOH sebanyak 3 tetes, jika terbentuk endapan maka identifikasi dapat dilanjutkan. Jika tidak terbentuk endapan maka sampel negatif mengandung ion Fe3+')
    st.write('7. Endapan kemudian dipisahkan, kemudian ditambahkan HNO3 sebanyak 5 tetes sampai larut')
    st.write('8. Larutan Fe3+ kemudian dibuktikan dengan ditambahkan SCN sebanyak 1 tetes hingga warna berubah menjadi merah jika warna berubah menjadi merah maka sampel terbukti mengandung ion Fe3+')
    st.write('9. Jika warna berubah menjadi merah maka identifikasi selesai dilakukan dan sampel positif mengandung ion Fe3+')
    st.image('https://acalpk.files.wordpress.com/2024/05/oip-1.jpeg?resize=219%2C219')
    st.write('Reaksi yang terjadi:')
    st.write('Fe3+ + NH4OH -> Fe(OH) (cokelat kemerahan) + NH4+')
    st.write('Fe(OH)3 (cokelat kemerahan) + HNO3 -> Fe3+ + 3NO3- + 3H2O')
    st.write('Fe3+ + SCN- -> Fe(SCN)3 (larutan merah)')
    
elif ion_identifikasi == "Ba2+":
    st.write('Alat dan Bahan : Tabung Reaksi, Pipet tetes, Tabung Sentrifugasi, NH4OH, HCl encer, Air Suling')
    st.write('Cara Kerja :')
    st.write('1. Cuci dan bilas tabung reaksi dengan air keran dan air suling, lalu dikeringkan')
    st.write('2. Masukkan sampel yang akan diidentifikasi ke dalam tabung reaksi sebanyak 1 drop')
    st.write('3. HCl encer dimasukkan sebanyak 1 drop kedalam tabung reaksi yang sudah diisikan sampel, lalu di centrifuge')
    st.write('4. Jika tidak terbentuk endapan maka identifikasi dapat dilanjutkan, jika terbentuk endapan maka sampel negatif mengandung ion Ba2+')
    st.write('5. Larutan ditambahkan NH4OH berlebih larutan akan tetap jernih, kemudian ditambahkan 3 drop K2CrO4 sebanyak sampai terbentuk endapan BaCrO4')
    st.write('6. Endapan BaCrO4 dipisahkan kemudian ditambahkan CH3COOH sampai terbentuk endapan putih')
    st.write('7. Jika terbentuk endapan kuning BaCrO4 maka identifikasi selesai dilakukan dan sampel positif mengandung ion Ba2+')
    st.image('https://acalpk.files.wordpress.com/2024/05/pe-1396637406-e1715527069239.webp?resize=219%2C219')
    st.write('Reaksi yang terjadi:')
    st.write('Ba2+ + K2CrO4 -> BaCrO4 (kuning) + 2K+')
    

elif ion_identifikasi == "Sr2+":
    st.write('Alat dan Bahan : Tabung Reaksi, Pipet tetes, Tabung Sentrifugasi, NH4OH, HCl encer, Air Suling')
    st.write('Cara Kerja :')
    st.write('1. Cuci dan bilas tabung reaksi dengan air keran dan air suling, lalu dikeringkan')
    st.write('2. Masukkan sampel yang akan diidentifikasi ke dalam tabung reaksi sebanyak 1 drop')
    st.write('3. HCl encer dimasukkan sebanyak 1 drop kedalam tabung reaksi yang sudah diisikan sampel, lalu di centrifuge')
    st.write('4. Jika tidak terbentuk endapan maka identifikasi dapat dilanjutkan, jika terbentuk endapan maka sampel negatif mengandung ion Sr2+')
    st.write('5. Larutan ditambahkan NH4OH berlebih larutan akan tetap jernih, kemudian ditambahkan 3 drop K2CrO4 sebanyak sampai terbentuk endapan SrCrO4')
    st.write('6. Endapan SrCrO4 dipisahkan kemudian ditambahkan CH3COOH sampai larut')
    st.write('7. Larutan ion Sr2+ ditambahkan 10 tetes Na2CO3 sampai terbentuk endapan kuning')
    st.write('8. Jika terbentuk endapan kuning SrCO3 maka identifikasi selesai dilakukan dan sampel positif mengandung ion Sr2+')
    st.image('https://acalpk.files.wordpress.com/2024/05/pe-1396637406-e1715527069239.webp?resize=219%2C219')
    st.write('Reaksi yang terjadi:')
    st.write('Sr2+ + K2CrO4 -> SrCrO4 (kuning) + 2K+')
    st.write('SrCrO4 (kuning) + CH3COOH -> Sr2+ + Cr2(O7)2- + H2O')
    st.write('Sr2+ + Na2CO3 -> SrCO3 (kuning) + 2Na+')

elif ion_identifikasi == "Ca2+":
    st.write('Alat dan Bahan : Tabung Reaksi, Pipet tetes, Tabung Sentrifugasi, NH4OH, HCl encer, Air Suling')
    st.write('Cara Kerja :')
    st.write('1. Cuci dan bilas tabung reaksi dengan air keran dan air suling, lalu dikeringkan')
    st.write('2. Masukkan sampel yang akan diidentifikasi ke dalam tabung reaksi sebanyak 1 drop')
    st.write('3. HCl encer dimasukkan sebanyak 1 drop kedalam tabung reaksi yang sudah diisikan sampel, lalu di centrifuge')
    st.write('4. Jika tidak terbentuk endapan maka identifikasi dapat dilanjutkan, jika terbentuk endapan maka sampel negatif mengandung ion Ca2+')
    st.write('5. Larutan ditambahkan NH4OH berlebih larutan akan tetap jernih, kemudian ditambahkan 3 drop K2CrO4 akan tetap larut')
    st.write('6. 10 tetes H2C2O4 dan 10 tetes NH4OH dihomogenkan dalam tabung lalu ditambahkan larutan Ca2+ sampai terbentuk endapan putih')
    st.write('7. Jika terbentuk endapan putih CaC2O4 maka identifikasi selesai dilakukan dan sampel positif mengandung ion Ca2+')
    st.image('https://acalpk.files.wordpress.com/2024/05/bild0113-1.jpg?resize=219%2C219')
    st.write('Reaksi yang terjadi:')
    st.write('H2C2O4 + NH4OH -> (NH4)2C2O4 + H2O')
    st.write('(NH4)2C2O4 + Ca2+ -> CaC2O4 (putih) + 2NH4+')
    st.write('Ca2+ + H2C2O4 + NH4OH -> CaC2O4 (putih) + 2NH4 + H2O')
